name: calabreso
description: "A new Flutter package project."
version: 0.0.3
homepage:

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: DSIcons1px
      fonts:
        - asset: assets/fonts/DSIcons1px.ttf

    - family: DSIcons2px
      fonts:
        - asset: assets/fonts/DSIcons2px.ttf

    - family: DSIconsFilled
      fonts:
        - asset: assets/fonts/DSIconsFilled.ttf
