name: calabreso
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: DSIcons
      fonts:
        - asset: assets/fonts/DSIcons.ttf
