/// Flutter icons DSIcons2px
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DSIcons2px
///      fonts:
///       - asset: fonts/DSIcons2px.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class DSIcons2px {
  DSIcons2px._();

  static const _kFontFam = 'DSIcons2px';
  static const String? _kFontPkg = 'calabreso';

  static const IconData adjustments = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert_circle = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert_triangle = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_sort = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_check = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_cog = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_exclamation = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_off = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_plus = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_search = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bolt_off = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bolt = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brand_speedtest = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brand_youtube = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_cog = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_due = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_event = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_month = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_plus = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_search = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_time = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_week = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_x = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_bolt = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_exclamation = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_plus = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData capture = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_crash = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checks = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_minus = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_plus = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_x = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_check = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_list = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_plus = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_text = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_x = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_edit = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_plus = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_x = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_download = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_off = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_upload = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData currency_dolar = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_mobile_down = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discount_check = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dots_vertical = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_closed = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_alert = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_analytics = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_check = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_description = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_download = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_export = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_import = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_invoice = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_minus = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_plus = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_search = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_text = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_type_csv = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_type_pdf = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_type_xls = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_upload = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData files = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_cog = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_edit = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_off = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_plus = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_x = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_search = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gas_station = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_square_rounded = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layout_cards = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layout_grid = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layout_list = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_photo = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_check = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_details = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_search = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_off = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_x = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_access = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_off = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin_check = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin_cog = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin_exclamation_1 = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin_exclamation = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin_off = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin_plus = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin_x = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_search = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_2 = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_cog = IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_dots = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_down = IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_exclamation = IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_heart = IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_minus = IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_off = IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_plus = IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_question = IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_report = IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_search = IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_share = IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_star = IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_up = IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_x = IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messages = IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_cancel = IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_edit = IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_exclamation = IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_off = IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_plus = IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_scan = IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_search = IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_x = IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo = IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrcode_off = IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrcode = IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_alert = IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_off = IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reload = IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report_analytics = IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report_search = IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report = IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_search = IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_ascending = IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_descending = IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_down = IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_up = IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timeline_event_exclamation = IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timeline_event_minus = IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timeline_event_plus = IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timeline_event_text = IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timeline_event_x = IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timeline_event = IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_x = IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trending_down = IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trending_up = IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_cancel = IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_check = IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_circle = IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_cog = IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_edit = IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_exclamation = IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_pin = IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_plus = IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_scan = IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_search = IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_x = IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users_group = IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users_plus = IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi_off = IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi = IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
