// ignore_for_file: constant_identifier_names, unnecessary_nullable_for_final_variable_declarations, dangling_library_doc_comments

/// Flutter icons DSIconsFilled
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DSIconsFilled
///      fonts:
///       - asset: fonts/DSIconsFilled.ttf
///
///
///
import 'package:flutter/widgets.dart';

class DSIconsFilled {
  DSIconsFilled._();

  static const _kFontFam = 'DSIconsFilled';
  static const String? _kFontPkg = 'calabreso';

  static const IconData alert_circle_filled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert_triangle_filled = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_filled_plus = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_filled_z = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_filled = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_filled = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discount_check_filled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_filled = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_filled = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_filled = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin_filled = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_filled = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_filled = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_up_filled = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_down_filled = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timeline_event_filled = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_filled = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
